sudo: required

services:
  - docker

language: node_js
node_js:
  - '10'

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

scripts:
  - cp .env.example .env
  - docker-compose up -d meta-db
  - npm install
  - npm test
